### ISSUE TITLE
Is this a Monterey or Big Sur build?

### ISSUE THREAD

**Issue by jbwharris** [alfatihart/Hackintosh-MSI-GL62M-7RDX#1]
Was just curious, have a similar laptop and have been struggling to get Monterey working

**Comment by jbwharris** [comment]
Just read further and say it mention Big Sur. Did you have any plans to get it running Monterey?

**Comment by alfatihart** [comment]
I've tried with monterey, but found problems with wifi, bluetooth on opencore 0.7.5, maybe I'll try again with the latest version. to stabilize now on big sur

**Comment by alfatihart** [comment]
hi, now i have updated it

**Comment by jbwharris** [comment]
Is that the same EFI that you were able to run the installer? I've been struggling with getting my installer to even boot for Monterey. I have a GL72M 7RDX, so I believe our builds should be almost identical aside from the screen size. I do have most of the things you have mentioned as not working functioning on [my build](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX), so might be worth checking out.

**Comment by alfatihart** [comment]
yes, I used it before for installation without additional patches. in your case maybe you can try my efi, of course adjust the kext for different parts
